# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/exynos9825-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter f62,$(TARGET_DEVICE)),)

endif
